### ISSUE TITLE
Handle installation path for libmaxminddb in configure

### ISSUE THREAD

**Issue by rainerjung** [maxmind/mod_maxminddb#10]
Let configure handle a on-standard installation path for libmaxminddb. Add a --with-libmaxminddb=PATH flag to configure. Pass along include and lib sub dirs to CFLAGS (-I/path/to/libmaxminddb/include) and LDFLAGS (-L/path/to/libmaxminddb/lib).

**Comment by oschwald** [comment]
The [GNU Coding Standards](http://www.gnu.org/prep/standards/standards.html) state: "Do not use a ‘--with’ option to specify the file name to use to find certain files. That is outside the scope of what ‘--with’ options are for."

Is there a reason why you can't just set `LDFLAGS` and `CFLAGS` directly?
