### ISSUE TITLE
Invalid compile flag '-Werror=format-extra-args'

### ISSUE THREAD

**Issue by marcstern** [maxmind/mod_maxminddb#101]
My pull request (https://github.com/marcstern/mod_maxminddb/actions/runs/1813351724) does not compile because of previously existing code.
```
mod_maxminddb.c: In function ‘export_env_for_database’:
mod_maxminddb.c:57:47: error: too many arguments for format [-Werror=format-extra-args]
   57 |         APLOG_MARK, APLOG_ERR, 0, server_rec, "[mod_maxminddb]: " __VA_ARGS__)
      |                                               ^~~~~~~~~~~~~~~~~~~
```
It seems that '-Werror=format-extra-args' is incompatible with the existing code

**Comment by oschwald** [comment]
I am closing this given the PR did seem to pass when the Action was run against this repo. Please let me know if you think this is a mistake.

**Comment by marcstern** [comment]
Yes, this is a mistake. The build uses '-Werror=format-extra-args' is incompatible with the existing code (and with httpd/apr which also use  __VA_ARGS__).

**Comment by horgh** [comment]
Why does compilation pass in this repo? I think the commit that failed in your repo has an extra argument:

https://github.com/marcstern/mod_maxminddb/commit/a4801965687f2ac450b02aa1ac059553513e5ab8#diff-9a4c7e6f52371723a94ca35bfb898a6b6a3b075014ca5b85d0f5d2f19bf1ae85R445-R446

**Comment by oschwald** [comment]
I am closing this again given the above comment.
