### ISSUE TITLE
Doesn't work IF compiled with PHP-FPM enabled, and then disabled?

### ISSUE THREAD

**Issue by crazyserb** [maxmind/mod_maxminddb#102]
For some reason, this worked just fine when compiled into Apache when PHP-FPM was enabled.

However, as soon as we disabled PHP-FPM and recompiled Apache/PHP, this stopped working.

And installing this module again doesn't help.

I see it loaded in Apache, but it's just not working on the front-end anymore whatsoever...

Any thoughts? What am I missing?

**Comment by oschwald** [comment]
Unfortunately, I can't think of a reason why PHP-FPM would cause this module to not work.

**Comment by oschwald** [comment]
I am closing this as it isn't actionable.
