### ISSUE TITLE
make install command Warning

### ISSUE THREAD

**Issue by Barnabas2** [maxmind/mod_maxminddb#105]
I have just installed the `libmaxminddb` and I tried installing the `mod_maxminddb-1.2.0.tar.gz` file by running first `./configure` and then `make install` but after the `make install` I got this warning:

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /opt/bitnami/apache2/htdocs/mod_maxminddb-1.2.0/missing aclocal-1
.15 
/opt/bitnami/apache2/htdocs/mod_maxminddb-1.2.0/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:326: aclocal.m4] Error 127
```

I don't know what I'm missing as Automake package is already installed on my server: `automake is already the newest version (1:1.16.1-4).`

**Comment by oschwald** [comment]
I don't think this is an issue with the distribution. As the message suggests, you should only need automake if you are modifying the m4/ac files. support@maxmind.com would likely be able to better help you diagnose this.
