### ISSUE TITLE
Compilation against Apache 2.4 on Solaris fails because APR_PATH_MAX is not defined

### ISSUE THREAD

**Issue by rainerjung** [maxmind/mod_maxminddb#11]
Compilation against Apache 2.4 on Solaris fails:

In file included from /path/to/apache/include/ap_hooks.h:39:0,
                 from /path/to/apache/include/ap_config.h:25,
                 from /path/to/apache/include/httpd.h:44,
                 from mod_maxminddb.c:25:
/path/to/apache/include/apr.h:597:2: error: #error no decision has been made on APR_PATH_MAX for your platform
 #error no decision has been made on APR_PATH_MAX for your platform
  ^
apxs:Error: Command failed with rc=65536
.
Makefile:381: recipe for target 'mod_maxminddb.so' failed

This is due to Apache 2.4 using gcc as a C99 compiler by default. On Solaris that means, that all non POSIX-Standard extensions are off by default. they have to get reenabled using the define -D__EXTENSIONS__.

For a related discussion see http://svn.haxx.se/dev/archive-2013-06/0448.shtml

**Comment by JavaJoeS** [comment]
Add to Makefile

EXTRA_CPPFLAGS = -D__EXTENSIONS__
