### ISSUE TITLE
Add support for X-Forwarded-For

### ISSUE THREAD

**Issue by donum** [maxmind/mod_maxminddb#26]
Hi,

in your description it says:

> This module uses the client IP address for the lookup. This is not always what you want. If you need to use an IP address specified in a header (e.g., by your proxy frontend), mod_remoteip may be used to set the client IP address.

However, the still wildly used Apache 2.2 doesn't include mod_remoteip.

I also see in your code:

```
static char *get_client_ip(request_rec *r)
{
# if AP_SERVER_MAJORVERSION_NUMBER == 2 && AP_SERVER_MINORVERSION_NUMBER == 4
    return r->useragent_ip;
# else
    return r->connection->remote_ip;
#endif
}
```

You tried to support both but the condition are commented out.

Could you please add support for 2.2 in this regard? Especially it would be cool if there were a config setting so that the module uses the client ip coming from the [X-Forwarded-For](http://en.wikipedia.org/wiki/X-Forwarded-For) header.

What do you think? We tried using a downgrade version of mod_remoteip which initially worked, but gives us **SIGTERM**s.

We would like to use a commercial license from you, but this technical issue is blocking us right now.

Thanks,
Daniel

**Comment by oschwald** [comment]
That code isn't commented out. It is preprocessor directives. For 2.2, you can use a backported version of mod_remoteip such as [mod_remoteip-httpd22](https://github.com/ttkzw/mod_remoteip-httpd22), which is what we use in our unit tests, or something like [mod_rpaf](https://github.com/gnif/mod_rpaf) may work as well.

**Comment by donum** [comment]
Oh sorry, I am not familiar with c. Thanks, I will check the links and respond later. mod_rpaf sounds really promising.

**Comment by tewner** [comment]
This feature was added in mod_geoip2 , including a feature we requested, "GeoIPUseFirstNonPrivateXForwardedForIP". We would like to stop using the "Legacy" MaxMind DB's, but would also prefer not to have this "regression".

https://github.com/maxmind/geoip-api-mod_geoip2/blob/master/mod_geoip.c#L388

**Comment by oschwald** [comment]
Is there a reason why you can't use `mod_remoteip`? Parsing various headers seems out of scope for this library.

**Comment by oschwald** [comment]
Closing as `mod_remoteip` can be used to handle this use case.
