### ISSUE TITLE
ENV variables set by mod_maxminddb are not visible within VirtualHost, but visible inside Directory or Location block

### ISSUE THREAD

**Issue by yaric1** [maxmind/mod_maxminddb#30]
First rewrite rule does not work, but exactly the same second does within same virtual host.

httpd.conf:
```
RemoteIPHeader IPTEST

<VirtualHost>

MaxMindDBEnable On

MaxMindDBFile CITY_DB /bigdisk0/geoip/share/GeoIP/GeoIP2-City.mmdb

MaxMindDBEnv GEOIP_REGION_CODE  CITY_DB/subdivisions/0/iso_code

 RewriteCond %{ENV:GEOIP_REGION_CODE} SH
 RewriteRule . http://www.some1.com/de/ww?ff=%{ENV:GEOIP_REGION_CODE} [L,R=301]

<Location />
 RewriteCond %{ENV:GEOIP_REGION_CODE} SH
 RewriteRule . http://www.some2.com/de/ww?ff=%{ENV:GEOIP_REGION_CODE} [L,R=301]
</Location>

</VirtualHost>
```

wget.exe --header "IPTEST: 77.6.124.167" -O - http://10.30.11.171/bin/env.cgi
 --2015-06-23 15:29:03-- http://10.30.11.171/bin/env.cgi
 Connecting to 10.30.11.171:80... connected.
 HTTP request sent, awaiting response... 301 Moved Permanently
 Location: http://www.some2.com/de/ww?ff=SH [following]
 --2015-06-23 15:29:03-- http://www.some2.com/de/ww?ff=SH

**Comment by lsergei** [comment]
Stuck with the same issue.

**Comment by oschwald** [comment]
Could you post your `httpd.conf`?

**Comment by lsergei** [comment]
My vhost config:
```
<VirtualHost *:80>
    ServerName "********.com"
    ServerAlias  "www.********.com"
    UseCanonicalName Off

    ServerAdmin  "sergii@——————.com"

    DocumentRoot "/var/www/vhosts/********.co/httpdocs"


        ############################################################################
        ###################### Country blocking v. 2.7 #############################
        ########################################
	 RewriteEngine on
        RewriteMap ip_whitelist_map dbm:/var/www/vhosts/********.co/httpdocs/ipdb.map
        RewriteCond %{ENV:MM_COUNTRY_CODE} !^AU$
        RewriteCond %{REQUEST_URI} !^/under_maintenance.html$  
        RewriteCond ${ip_whitelist_map:%{REMOTE_ADDR}} !^a$
        RewriteRule ^(.*)$ http://www.********.com/under_maintenance.html [R,L]
        ######## Country blocking ends here ########################################

    <Directory /var/www/vhosts/********.co/httpdocs>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
</VirtualHost>
```

MM_COUNTRY_CODE is set in geoip.conf.

It works like a charm if used with geoip2/Legacy database, but if I switch from mod_geoiop2/legacy to mod_maxmindmmdb/MMDB it works only in .htaccess or PHP or elsewhere, but not in the root of vhost config.

**Comment by rafl** [comment]
I believe this has been addressed in https://github.com/maxmind/mod_maxminddb/commit/8f87e1865821c765ff91c85f0d8b9e540dec8ca0

**Comment by yaric1** [comment]
I compiled from master and what a relief :) Confirmed, fixed! Thank you guys, you saved us!
Finally we can migrate from mod_geoip2 to mod_maxminddb

**Comment by rafl** [comment]
You're welcome. Thanks so much for bringing this to our attention!

Closing this issue.
