### ISSUE TITLE
MaxMindDBEnv not showing up in PHP

### ISSUE THREAD

**Issue by xoogu** [maxmind/mod_maxminddb#31]
In my Virtualhost config I have:
```
MaxMindDBEnable On
MaxMindDBFile COUNTRY_DB /path/to/GeoLite2-Country.mmdb
MaxMindDBEnv GEOIP_COUNTRY_CODE COUNTRY_DB/country/iso_code
```
But when I look at a PHP info page, there is no `$_SERVER['GEOIP_COUNTRY_CODE']` variable listed.
The following two variables are listed though, so it seems the GeoIP lookup is working, just not setting the GEOIP_COUNTRY_CODE variable (or if it is being set, not passing it on to PHP):
```
$_SERVER['MMDB_INFO']	lookup success
$_SERVER['MMDB_ADDR']	127.0.0.1
```
I'm checking this from my local machine (as you can tell), so I'm not sure if that is having an effect. I was expecting to see `$_SERVER['GEOIP_COUNTRY_CODE']` listed in PHP, but with no value.

**Comment by oschwald** [comment]
Please try with a public IP that is in the GeoLite2 database.

**Comment by xoogu** [comment]
I can't try on a live server, so in my Virtualhost config I added:
```
RemoteIPHeader X-Fake-IP
RemoteIPTrustedProxy my.local.ip.address
```
And then I sent a request with the X-Fake-IP header set to 123.123.123.123
That gave the following in PHP:
```
$_SERVER['GEOIP_COUNTRY_CODE'] CN 
$_SERVER['MMDB_INFO'] result found 
$_SERVER['MMDB_ADDR'] 123.123.123.123 
```
So it looks like the GEOIP_COUNTRY_CODE environment variable is either not being set when no value is found (I would expect it to be set, but with an empty value), or it is not being passed to PHP when it is empty.

**Comment by hanafiah** [comment]
I have similar issue, non of the Env appear except for the MMB_INFO & MMDB_ADDR

Here is my conf
````
    MaxMindDBEnable On
    MaxMindDBFile COUNTRY_DB /usr/share/GeoIP/GeoLite2-Country.mmdb
    MaxMindDBFile CITY_DB    /usr/share/GeoIP/GeoLite2-City.mmdb

    MaxMindDBEnv COUNTRY_CODE COUNTRY_DB/country/iso_code
    MaxMindDBEnv REGION_CODE  CITY_DB/subdivisions/0/iso_code

    MaxMindDBEnv MM_COUNTRY_CODE CITY_DB/country/iso_code
    MaxMindDBEnv MM_COUNTRY_NAME CITY_DB/country/names/en
    MaxMindDBEnv MM_CITY_NAME CITY_DB/city/names/en
    MaxMindDBEnv MM_LONGITUDE CITY_DB/location/longitude
    MaxMindDBEnv MM_LATITUDE CITY_DB/location/latitude
````

here is result from phpinfo()
````
_SERVER["MMDB_ADDR"]	10.224.0.67
_SERVER["MMDB_INFO"]	lookup success
````

**Comment by oschwald** [comment]
@hanafiah, `10.224.0.67` is a private IP. There won't be any data for it in the database.

**Comment by hanafiah** [comment]
@oschwald, so it wont show any environment variable if no data for that? I can't see MM_CITY_NAME in phpinfo() either. By right I suppose to see the variables with no data right?.

**Comment by oschwald** [comment]
Yes, it only exports the environment variable if that path exists in the database.

**Comment by xoogu** [comment]
Can this fact be added to the documentation, because it's not obvious behaviour?
