### ISSUE TITLE
Solaris 11: libmaxminddb not able to return latitude/longitude

### ISSUE THREAD

**Issue by tkuenster** [maxmind/mod_maxminddb#39]
mmdblookup -i 72.229.28.185
"location": 
      {
        "latitude": 
          0.000000 <double>
        "longitude": 
          0.000000 <double>
        "metro_code": 
          501 <uint16>
        "time_zone": 
          "America/New_York" <utf8_string>
      }

On linux, the same database does return lat/lon.

Another clue - make check gives some errors data_entry_list_t:
not ok 25 - double value was approximately 42.123456
#   Failed test 'double value was approximately 42.123456'
#   at maxminddb_test_helper.c line 239.
#   got 0.000000 but expected 42.123456 (diff = 42.123456)
ok 26 - found a map key
ok 27 - 'float' key's value is a float
not ok 28 - float value was approximately 1.1

data_types_t fails with similar issues:
not ok 84 - double value was approximately 42.123456
#   Failed test 'double value was approximately 42.123456'
#   at maxminddb_test_helper.c line 239.
#   got -87750184517491777524722039008539763058909340248586710645163828237927168013861995082144228853051998053752430466495949184291917310566362668094376567441251470065827607880193526468881177217420597114227413315941419592173074085574369360097342313439831655682505571750611965220873252074818033024057211773727539200.000000 but expected 42.123456 (diff = 87750184517491777524722039008539763058909340248586710645163828237927168013861995082144228853051998053752430466495949184291917310566362668094376567441251470065827607880193526468881177217420597114227413315941419592173074085574369360097342313439831655682505571750611965220873252074818033024057211773727539200.000000)
ok 85 - no error from call to MMDB_vget_value - float field for ::4.5.6.7 - mmap mode
ok 86 - got the expected data type - float field for ::4.5.6.7 - mmap mode
not ok 87 - float value was approximately 1.1
#   Failed test 'float value was approximately 1.1'
#   at maxminddb_test_helper.c line 249.
#   got -NaN but expected 1.1 (diff = NaN)

I wish I had some c skills to fix this - I'm assuming it's an issue with some library returning some floats or doubles in a way that maxmind doesn't like on the Solaris OS.

Any ideas?

**Comment by oschwald** [comment]
This sounds like a bug with [libmaxminddb](https://github.com/maxmind/libmaxminddb/issues), not mod_maxminddb. Would you mind moving it there?
