### ISSUE TITLE
Accessing mmdb info thats not in the examples (i.e. Metro Code) 

### ISSUE THREAD

**Issue by eorbach** [maxmind/mod_maxminddb#44]
i'm trying to understand if i'd like to set an environment variable for 'Metro Code' how do I know how to set it.
Looking at the given examples for MaxMindDBEnv I do not understand how do i know the key name/path in the mmdb for the various info that i see exists in the mmdb

MaxMindDBEnv MY_DMA CITY_DB/Metro_Code 
or
MaxMindDBEnv MY_DMA CITY_DB/locations/metro_code
or whatever
how would i go about finding out how to set this parameter correctly?

**Comment by oschwald** [comment]
```
MaxMindDBEnv MY_DMA CITY_DB/location/metro_code
```
Note that there is no `s` after `location`.

Generally speaking, you can see the structure of the database by using `mmdblookup`.
