### ISSUE TITLE
Seperate env and path

### ISSUE THREAD

**Issue by waghanza** [maxmind/mod_maxminddb#48]
Hi,

I want to use `GeoIP2` functions on a multi-enviroment app.

To do this I want to split `mod_maxminddb` configuration in 2 parts :

* write the full `.mmdb` file path
* use the `MaxMindDBFile`

is there a way to do this ?

* On one hand, I want to use `MaxMindDBEnv` on my **.htacess** (since I want the same configuration on all my environments).
* In the other hand, I want to devine `COUNTRY_DB` path on each environments (since **path** could vary)

Is there a way to do this ?

Regards,

**Comment by oschwald** [comment]
I am not sure if I fully understand the use case, but it should be possible to split the configuration. Could you give an example configuration of what you have tried in particular?

**Comment by waghanza** [comment]
of course

I have :

+ in a **main** configuration file

~~~
<IfModule mod_maxminddb.c>
  MaxMindDBEnable On
  MaxMindDBFile COUNTRY_DB <FILE_PATH>
</IfModule>
~~~
+ in  my **.htaccess**

~~~
<IfModule mod_maxminddb.c>
    MaxMindDBEnv COUNTRY_CODE COUNTRY_DB/country/iso_code
</IfModule>
~~~

**Comment by oschwald** [comment]
As far as I know, that should work. We have a [unit test](https://github.com/maxmind/mod_maxminddb/blob/master/t/htaccess.t) for almost exactly that scenario.

**Comment by waghanza** [comment]
@oschwald unfortunaletly, it does not work 

I mean `apache` dosnot expose `COUNTRY_CODE` if configuration is splitted, perhaps it's a configuration defined behavior 

PS : I'm on **apache** `2.4`

**Comment by oschwald** [comment]
Given that it is tested on 2.4 and the test seems to pass, I would suggest following up with [support@maxmind.com](mailto:support@maxmind.com) if you are a paying customer or [StackOverflow](https://stackoverflow.com/) if you use GeoLite2.
