### ISSUE TITLE
How to install mod_maxminddb in windows

### ISSUE THREAD

**Issue by abhishekdoshi** [maxmind/mod_maxminddb#49]
I am using Windows Server, so how can i install this module in windows ?

**Comment by horgh** [comment]
Hi @abhishekdoshi. I don't have a Windows environment set up to work out exact instructions for you at this time. I'll have to get back to you, likely later this week.

In the mean time, I did find some possibly relevant [instructions in a blog post](https://www.calazan.com/how-to-compile-and-build-apache-modules-on-windows-using-visual-studio/) about building other Apache modules. Using that together with info [from the Apache site](https://httpd.apache.org/docs/2.4/platform/win_compiling.html), it may be possible to figure this out.

We have [some info](https://github.com/maxmind/libmaxminddb/blob/master/projects/VS12/README.md) about building a related library on Windows that could prove useful as well.
