### ISSUE TITLE
./configure

### ISSUE THREAD

**Issue by ZAJDAN** [maxmind/mod_maxminddb#57]
Hello...
I downloaded zip version and now I am trying to install on Debian 8, but configure returns me:
```
root@webserver:/home/webmaster/mod_maxmind# ./configure
bash: ./configure: No such file or directory
```
after a few minutes I have found that firstly I have to call command '**autoconf**' which depends on packages: **m4, automake**, so I installed it.
Please, You should write this into installation information.

Now Iam facing another problem:
`webmaster@webserver:~/mod_maxmind/mod_maxminddb-master$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in . "."/.
`
thanks for any hint

**Comment by nchelluri** [comment]
Hi;

From our [Installation section](https://github.com/maxmind/mod_maxminddb#installation):

> If you are compiling the module from a Git checkout, you must have automake, autoconf, and libtool installed and you must run ./bootstrap before running configure.

Unfortunately, this is not super clear apparently; do you have any suggestions on how to make it clearer?

**Comment by nchelluri** [comment]
Also when you say you downloaded a "zip" do you mean from https://github.com/maxmind/mod_maxminddb/releases? Then my suggestion would make sense; otherwise I am not sure.

**Comment by nchelluri** [comment]
HI @ZAJDAN after talking with a co-worker the issue is that we shouldn't be offering the .zip file - instead you want to download https://github.com/maxmind/mod_maxminddb/releases/download/1.1.0/mod_maxminddb-1.1.0.tar.gz - the first file on the Releases page. We should not be offering the zip file but can't find a way to disable it.

**Comment by nchelluri** [comment]
To be totally clear, we recommend **always downloading the .tar.gz** from the Releases page.

Many people run into issues with the `bootstrap` script included in the source code (.zip) file, and it is not compatible with all versions of the automake toolset. So, please download the .tar.gz. Thanks!

**Comment by ZAJDAN** [comment]
I recommend in **Installation section** put the information about what is needed(automake,libtool,etc) as first section and then put the steps/commands. Because people like me and I think it is standard, doesn't read from down to top .

**Comment by oschwald** [comment]
If you download the release tarball, e.g., `mod_maxminddb-1.1.0.tar.gz`, you shouldn't need those. You only need them if you are building directly from the Git source. It is somewhat confusing as GitHub includes the Git source on the release pages with no apparent way of disabling it.

**Comment by ZAJDAN** [comment]
I do not know if anybody else, but for me is automatic click on the green button Download and choose there the .**zip.**
Now I already downloaded the **tar** from the section releases and successfully installed.
Thanks boys!
