### ISSUE TITLE
How to install on Easyapache 4 ?

### ISSUE THREAD

**Issue by phi148** [maxmind/mod_maxminddb#61]
Does anybody by chance know how to install this custom module on Easyapache 4?

Any help would be great, I'd love to use this module that I stumbled across today!

Thanks

**Comment by oschwald** [comment]
Sorry for the delayed response. From [the EasyApache documentation](https://documentation.cpanel.net/display/EA/Apache+Modules), it looks like it is not currently possible to install this module with it. You would likely need to ask cPanel to explicitly add support for the module.
