### ISSUE TITLE
MaxMindDBEnv format for all map keys

### ISSUE THREAD

**Issue by marcstern** [maxmind/mod_maxminddb#71]
Can we have the exhaustive list of all keys available in commercial DBs, like anonymous IPs?
Thanks

**Comment by horgh** [comment]
Unfortunately we don't currently, though I agree it'd be useful.

One way you can look at what possible keys there are is using mmdblookup from libmaxminddb to look up IPs. This won't be exhaustive, but it can be helpful in exploring the databases. Another way is to look at what our libraries that interact with the databases do. e.g., https://github.com/maxmind/GeoIP2-php/blob/master/src/Model/AnonymousIp.php

**Comment by oschwald** [comment]
Closing as this is not specific to this API. I would suggest raising this with support.
