### ISSUE TITLE
Library using private IP and not public IP to determine location

### ISSUE THREAD

**Issue by ridhish1991** [maxmind/mod_maxminddb#72]
Facing issue with GeoIP legacy database lookup. MMDB_ADDR always uses private IP and not the public IP address to determine location of IP.

Here are the steps we followed.

1. Followed all the steps and installed mod_maxminddb from here.
https://github.com/maxmind/mod_maxminddb

2. Added below code in .htaccess to enable MaxMind apache module.

MaxMindDBEnable On
MaxMindDBFile CITY_DB /<path_to_db>/GeoIP2-City.mmdb
MaxMindDBEnv MM_COUNTRY_CODE CITY_DB/country/iso_code
MaxMindDBEnv MM_STATE_CODE CITY_DB/subdivisions/0/iso_code

3. Trying to read MMDB_ADDR like this in PHP script.

echo $_SERVER['MMDB_ADDR'];

This is printing private IP "10.0.0.84"
while public IP address is "52.42.80.12".

Because of this not getting anything in MM_COUNTRY_CODE and MM_STATE_CODE.

I believe it must use public IP address so that location of user can be determined.

Can you please help me out on this and tell me where I'm going wrong or anything specific I need to update on server?

**Comment by nchelluri** [comment]
Hello,

It seems like your webserver is probably behind a proxy/load balancer frontend. If you look at the [Usage section](https://github.com/maxmind/mod_maxminddb#usage)  of the README, we suggest using [mod_remoteip](http://httpd.apache.org/docs/current/mod/mod_remoteip.html) to fix this issue. Good luck!
