### ISSUE TITLE
UTF-8 chars are escaped in Apache logs

### ISSUE THREAD

**Issue by AdamPerkins** [maxmind/mod_maxminddb#73]
With mod_maxminddb module UTF-8 chars are escaped in Apache logs. (Escaping is called a 'feature' on Apaches side.)

f.ex.  
US Kalifornien San Jos\xc3\xa9
FR \xc3\x8ele-de-France Paris

With GeoIP module it was correct:
US California San Jose
FR Ile-de-France Paris

But I had before also a directive GeoIPEnableUTF8 On witch doesn't exist anymore.

**Comment by oschwald** [comment]
As you say, I believe this is a feature of Apache. The legacy names you give are not escaped as they are ASCII characters. I think you would need to disable escaping in Apache to resolve this.
