### ISSUE TITLE
Support for Precision

### ISSUE THREAD

**Issue by Rehtael** [maxmind/mod_maxminddb#79]
Great development, unfortunately the Lite MMDB's are still well behind in updates (especially ASN - now 2+ months since last update). Would be nice to be able to use the Precision City service. I understand this would add latency to Apache connections, but the lookup data would at least be current. Something like:

```
<IfModule mod_maxminddb.c>
	MaxMindDBEnable On
	MaxMindDBPrecision ACCOUNT_ID 00000
	MaxMindDBPrecision LICENSE_KEY xxxxxxxxxxxxxxxxxxxxxx
	MaxMindDBEnv MM_COUNTRY_CODE CITY_PS/country/iso_code
	MaxMindDBEnv MM_COUNTRY_NAME CITY_PS/country/names/en
	MaxMindDBEnv MM_CITY_NAME CITY_PS/city/names/en
	MaxMindDBEnv MM_LONGITUDE CITY_PS/location/longitude
	MaxMindDBEnv MM_LATITUDE CITY_PS/location/latitude
	MaxMindDBEnv MM_ASN CITY_PS/traits/autonomous_system_number
	MaxMindDBEnv MM_ASORG CITY_PS/traits/autonomous_system_organization
</IfModule>
```

Example of full [response.json.txt](https://github.com/maxmind/mod_maxminddb/files/3010355/response.json.txt)

**Comment by klp2** [comment]
The GeoLite2 databases should all be updated weekly, and when I attempt to download the most recent ASN database I see that it is from this week. Are you seeing something different?

**Comment by Rehtael** [comment]
GeoLite2-ASN.tar.gz 2019-03-26 00:55 = GeoLite2-ASN.mmdb 2019-01-04 10:24

**Comment by Rehtael** [comment]
Actually, think there might be something dodgy in my extract script....
