### ISSUE TITLE
Question about Config

### ISSUE THREAD

**Issue by kokotko1337** [maxmind/mod_maxminddb#80]
I used GEOIP and i want to switch to GeoLite. 

I have Question about CFG. 

Target is: Block all Countries, Allow only whitelisted + Allow IPs and IP Ranges

Is this right ? I did not found Documatation about IP blocking.

Config File:

MaxMindDBEnable On 
MaxMindDBFile DB /usr/local/share/GeoIP/GeoLite2-Country.mmdb
MaxMindDBEnv MM_COUNTRY_CODE DB/country/iso_code

Deny from all
Allow from env=AllowCountry

##### Whitelisted Country
SetEnvIf MM_COUNTRY_CODE DE AllowCountry

##### Some  WHITELISTED IP RANGES
Allow from 10.0.0.0/8
Allow from 192.0.0.0/8

##### Some  WHITELISTED IPs
Allow from 8.8.8.8

**Comment by oschwald** [comment]
As this is not a request for features or a report of a bug, I am going to go ahead and close this. At a glance, the config looks ok.
