### ISSUE TITLE
Raspberry Pi compatible?

### ISSUE THREAD

**Issue by ca13ra1** [maxmind/mod_maxminddb#87]
I’ve attempted to install on Raspbian Buster. Installed libmaxminddb using the Ubuntu method, installed fine. I compiled the Apache module, loaded it and installed the db needed in the correct directory. Ran the configtest and syntax OK. I wrote a quick php snippet, getting the country code variable and it seems to always say US (even if I use a VPN). I’ve also tested blocking countries without luck. 

Is this at all possible to run on the Raspberry Pi? More a generalized question and can be closed whenever you get a chance.

**Comment by oschwald** [comment]
This should work fine on Raspberry Pi. Are you sure it is using the correct IP in the lookup? If you are using a reverse proxy or something similar, you may need to use `mod_remoteip` as discussed in the documentation.

**Comment by ca13ra1** [comment]
All fixed and working correctly.It was an issue with me forgetting Cloudflare was on my domain. Thanks @oschwald
