### ISSUE TITLE
apache2.conf vs maxminddb.conf

### ISSUE THREAD

**Issue by p1r473** [maxmind/mod_maxminddb#89]
I've just done about an hour of testing of
`/etc/apache2/mods-available/maxminddb.conf `
vs
`/etc/apache2/apache2.conf `

I have come to the realization that all of the configuration must be in apache2.conf and maxminddb.conf can be completely empty 0byte file.
As of right now, I am working perfectly fine with:

```apache2.conf:```
```
<Directory /var/www/apache/>
        Options Indexes SymLinksIfOwnerMatch
        AllowOverride None
        Require all granted
	<IfModule mod_maxminddb.c>
		MaxMindDBEnable On
		MaxMindDBFile DB /usr/local/share/GeoIP/GeoLite2-Country.mmdb
		MaxMindDBEnv MM_COUNTRY_CODE DB/country/iso_code

		#SetEnvIf MM_COUNTRY_CODE ^(CN|RU|KP|IQ|IR|SY) BlockCountry
		#Deny from env=BlockCountry
		SetEnvIf MM_COUNTRY_CODE ^(CA|US|SG|GB|NL|DE|IE|JP|AU|BR) AllowCountry
		Allow from env=AllowCountry
	</IfModule>
</Directory>
```

and
maxminddb.conf totally empty.

I am just wondering if this is working as intended? 
If I move any of the following FROM apache2.conf TO maxminddb.conf, geoblocking stops working.
```
MaxMindDBEnable On
MaxMindDBFile DB /usr/local/share/GeoIP/GeoLite2-Country.mmdb
MaxMindDBEnv MM_COUNTRY_CODE DB/country/iso_code
```

**Comment by horgh** [comment]
I don't think it matters which file you have the directives in, as long as apache is instructed to include the file. I don't think we include any maxminddb.conf. Was the maxminddb.conf you mentioned being included by apache?

**Comment by p1r473** [comment]
That file is it mods-available.  It gets enabled when you load the module with a2modenable. The directives only work in Apache.conf because putting them in maxminddb.conf doesn't do anything.

**Comment by horgh** [comment]
Can you share your apache2.conf? Is this using Ubuntu's packaged apache?

**Comment by p1r473** [comment]
Apache2.conf: https://pastebin.com/raw/yQJTHHkB
maxminddb.conf: /etc/apache2/mods-available/maxminddb.conf 0byte empty file

I installed Apache on my TinkerOS installation

**Comment by p1r473** [comment]
When I do a2dismod maxminddb, the symlinks for /etc/apache2/mods-enabled for both maxminddb.conf and maxminddb.load are removed (they are still in /mods-available)

So, I am required to keep this empty 0kb, because without it (a2dismod maxminddb), the file isnt symlinked

BTW, maxminddb.load contains: 
```LoadModule maxminddb_module   /usr/lib/apache2/modules/mod_maxminddb.so```

**Comment by p1r473** [comment]
I've made some progress-
I've had to put the following in my apache2.conf in order to work:
```
<IfModule !mod_maxminddb.c>
		LoadModule maxminddb_module /usr/lib/apache2/modules/mod_maxminddb.so
	</IfModule>
```

Where is the module SUPPOSED to be loaded?

**Comment by p1r473** [comment]
I think my problem was the README documentation did not mention anywhere to have LoadModule maxminddb_module /usr/lib/apache2/modules/mod_maxminddb.so added

**Comment by horgh** [comment]
Yeah, I think the `LoadModule` part was implied as it is not specific to this module, rather it is how apache modules work generally. Adding something to the README about it seems fine.

As far as where it goes: In Ubuntu (and maybe other Debian based) packaged apaches, I believe the norm is to have the `LoadModule` line in an `/etc/apache2/mods-available/<modulename>.load`, which then gets symlinked to from `/etc/apache2/mods-enabled/<modulename>.load` when you run `a2enmod`, but it doesn't really matter if you follow that convention or not (though it's probably easier to stick to it).

I'm not sure where `/etc/apache2/mods-available/maxminddb.conf` came from. I'm not familiar with anything creating that automatically, but I don't think it is required nor will hurt anything.

**Comment by p1r473** [comment]
The maxminddb.conf for sure came from an old version
Thanks, I did not know about the module.load. 
@horgh Is the .load part included in the install? The installer should definitely have this file if it doesn't

**Comment by horgh** [comment]
Yes, installing creates it. It happens when we call apxs2 from what I can tell, so I'm guessing the Ubuntu/Debian packaging handles it automatically!

**Comment by p1r473** [comment]
Thanks!
